title: Brent Codes
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Brent Phillips # add your name
author_img: https://media.licdn.com/dms/image/C4E03AQHQsDJKpKjXXA/profile-displayphoto-shrink_200_200/0?e=1531958400&v=beta&t=PkY8h9-7hicYqZ57jPHfOc_4eDOTAqOx9sC1GM7fAQA # add your photo
about_author: >- 
  This website serves as an online presence. It will include
  my resume, demos of things I have created, an about me section
  if you care to get to know me better and tips and tricks about 
  programming as I can dream them up.
social_twitter: # add your Twitter handle
social_facebook: # add your Facebook handle
social_github: webdevbrent # add your Github handle
social_linkedin: # add your Linkedin handle
social_email: webdeveloperbrent@gmail.com # add your Email address

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  demos:
    output: true
    permalink: /my-demos/:path/

# SASS
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
